from sqlalchemy.types import NUMERIC, SMALLINT, INTEGER, VARCHAR, Boolean, DATE, TIMESTAMP

TABLE_SCHEMA = {
    'cuoc_phi': {
        "carrier_id": SMALLINT,
        "carrier": VARCHAR(length=20),
        "gt": INTEGER,
        "lt_or_eq": INTEGER,
        "order_type": VARCHAR(length=30),
        "service_fee": INTEGER,
        "import_time": TIMESTAMP,
    },
    'buu_cuc_best': {
        'receiver_province': VARCHAR(length=30),
        'receiver_district': VARCHAR(length=30),
        'n_post_offices': SMALLINT,
        "import_time": TIMESTAMP,
    },
    'buu_cuc_ghn': {
        'receiver_province': VARCHAR(length=30),
        'receiver_district': VARCHAR(length=30),
        'n_post_offices': SMALLINT,
        "import_time": TIMESTAMP,
    },
    'buu_cuc_ghtk': {
        'receiver_province': VARCHAR(length=30),
        'receiver_district': VARCHAR(length=30),
        'n_post_offices': SMALLINT,
        "import_time": TIMESTAMP,
    },
    'buu_cuc_ninja_van': {
        'receiver_province': VARCHAR(length=30),
        'receiver_district': VARCHAR(length=30),
        'n_post_offices': SMALLINT,
        "import_time": TIMESTAMP,
    },
    'chat_luong_noi_bo_njv': {
        'receiver_province': VARCHAR(length=30),
        'receiver_district': VARCHAR(length=30),
        "njv_post_office": VARCHAR(length=100),
        "delivery_success_rate": NUMERIC(3, 2),
        "is_more_than_100": Boolean,
        "import_time": TIMESTAMP,
    },
    'danh_gia_zns': {
        'receiver_province': VARCHAR(length=30),
        'receiver_district': VARCHAR(length=30),
        "carrier": VARCHAR(length=20),
        "n_messages": SMALLINT,
        "n_stars": SMALLINT,
        'comment': VARCHAR(length=200),
        'review': VARCHAR(length=200),
        'review_at': TIMESTAMP,
        "import_time": TIMESTAMP,
    },
    'giao_dich_combine_valid': {
        'carrier_created_at': TIMESTAMP,
        'order_id': VARCHAR(length=30),
        'carrier': VARCHAR(length=20),
        'weight': INTEGER,
        "sender_province": VARCHAR(length=30),
        "sender_district": VARCHAR(length=30),
        "receiver_province": VARCHAR(length=30),
        "receiver_district": VARCHAR(length=30),
        "order_status": VARCHAR(length=40),
        "order_type": VARCHAR(length=30),
        "order_type_id": SMALLINT,
        "sys_order_type_id": SMALLINT,
        "n_deliveries": SMALLINT,
        "delivery_type": VARCHAR(length=30),
        "is_returned": Boolean,
        "finished_at": TIMESTAMP,
        "import_time": TIMESTAMP,
    },
    'ngung_giao_nhan': {
        "receiver_province": VARCHAR(length=30),
        "receiver_district": VARCHAR(length=30),
        "carrier": VARCHAR(length=20),
        "status": VARCHAR(length=30),
        "import_time": TIMESTAMP,
    },
    'phan_vung_nvc': {
        "carrier": VARCHAR(length=20),
        "receiver_province": VARCHAR(length=30),
        "receiver_district": VARCHAR(length=30),
        "outer_region": VARCHAR(length=30),
        "inner_region": VARCHAR(length=30),
        "import_time": TIMESTAMP,
    },
    'data_api': {
        'id': INTEGER,
        'receiver_province_id': VARCHAR(length=2),
        'receiver_district_id': VARCHAR(length=3),
        'carrier_id': SMALLINT,
        'order_type_id': SMALLINT,
        "carrier_status": SMALLINT,
        "carrier_status_comment": VARCHAR(length=200),
        "estimate_delivery_time_details": NUMERIC(5, 2),
        "estimate_delivery_time": VARCHAR(length=30),
        "fastest_carrier_id": SMALLINT,
        "highest_score_carrier_id": SMALLINT,
        "customer_best_carrier_id": SMALLINT,
        "total_order": SMALLINT,
        "delivery_success_rate_id": SMALLINT,
        "delivery_success_rate": NUMERIC(5, 2),
        "score": NUMERIC(3, 2),
        "stars": NUMERIC(2, 1),
        "import_date": VARCHAR(length=10),
    },
    'data_api_full': {
        'id': INTEGER,
        'receiver_province_id': VARCHAR(length=2),
        "receiver_province": VARCHAR(length=30),
        'receiver_district_id': VARCHAR(length=3),
        "receiver_district": VARCHAR(length=30),
        'carrier_id': SMALLINT,
        "carrier": VARCHAR(length=20),
        'order_type_id': SMALLINT,
        "order_type": VARCHAR(length=30),
        "carrier_status": SMALLINT,
        "carrier_status_comment": VARCHAR(length=200),
        "estimate_delivery_time_details": NUMERIC(5, 2),
        "estimate_delivery_time": VARCHAR(length=30),
        "fastest_carrier_id": SMALLINT,
        "highest_score_carrier_id": SMALLINT,
        "customer_best_carrier_id": SMALLINT,
        "customer_best_carrier": VARCHAR(length=20),
        "total_order": SMALLINT,
        "delivery_success_rate_id": SMALLINT,
        "delivery_success_rate": NUMERIC(5, 2),
        "score": NUMERIC(3, 2),
        "stars": NUMERIC(2, 1),
        "import_date": VARCHAR(length=10),
    },
    'data_check_output': {
        'id': INTEGER,
        'order_id': VARCHAR(length=30),
        'sender_province_id': VARCHAR(length=2),
        "sender_province": VARCHAR(length=30),
        'sender_district_id': VARCHAR(length=3),
        "sender_district": VARCHAR(length=30),
        'receiver_province_id': VARCHAR(length=2),
        "receiver_province": VARCHAR(length=30),
        'receiver_district_id': VARCHAR(length=3),
        "receiver_district": VARCHAR(length=30),
        'carrier_id': SMALLINT,
        "carrier": VARCHAR(length=20),
        'order_type_id': SMALLINT,
        "order_type": VARCHAR(length=30),
        "sys_order_type_id": SMALLINT,
        "weight": INTEGER,
        "service_fee": INTEGER,
        "delivery_type": VARCHAR(length=30),
        "carrier_status": SMALLINT,
        "carrier_status_comment": VARCHAR(length=200),
        "estimate_delivery_time_details": NUMERIC(5, 2),
        "estimate_delivery_time": VARCHAR(length=30),
        "delivery_success_rate_id": SMALLINT,
        "delivery_success_rate": NUMERIC(5, 2),
        "customer_best_carrier_id": SMALLINT,
        "customer_best_carrier": VARCHAR(length=20),
        "partner_best_carrier_id": SMALLINT,
        "partner_best_carrier": VARCHAR(length=20),
        "cheapest_carrier_id": SMALLINT,
        "fastest_carrier_id": SMALLINT,
        "highest_score_carrier_id": SMALLINT,
        "score": NUMERIC(3, 2),
        "stars": NUMERIC(2, 1),
        "import_date": VARCHAR(length=10),
    }
}